//! First-run setup wizard (§2.6/§3.11's wizard flow), driven by this
//! TUI as its own interface — not a new one.
//!
//! Speaks the real wire protocol now: `operator_auth_client::setup`
//! against the watchdog's real `Operator_auth_server` socket. ADR-0057
//! built the server-side protocol; ADR-0058's own retrospective
//! ("Finding 5") is what caught this file never having been updated to
//! speak it, still self-contained standalone/demo mode; ADR-0059 is
//! this file's own rewrite that closes that gap. There is no more
//! in-process demo state here: no
//! locally-generated token, no locally-held hash. The token is read
//! straight off disk (the watchdog is the only thing that ever writes
//! it — §2.6), and every verify/burn decision is the real watchdog's,
//! not this process's.
//!
//! §3.11's own wording: "(1) submit the setup token (read from
//! `/etc/fossh/setup-token`), (2) enroll the real public key — either
//! paste an existing one or let foSSH generate a fresh keypair and
//! display the private half exactly once, (3) confirm enrollment, at
//! which point the token file is deleted and the stored hash
//! invalidated." All three steps here are real:
//!
//! 1. `Step::ReadyToSubmit` holds the plaintext this process already
//!    read from `token_path` at construction time (or `Step::NoTokenFound`
//!    / `Step::Failed` for a genuinely missing/unreadable file).
//! 2. `Step::ChoosingKeySource` branches into `Step::PastingKey` (raw
//!    armored-text input) or a blocking call to
//!    `operator_auth_client::generate_fresh_operator_key` (real
//!    `gpg --quick-generate-key`, landed in the operator's own default
//!    keyring — see that function's own doc comment for why nowhere
//!    else will do — shown once as `Step::KeyGenerated`).
//! 3. Either path ends by calling `operator_auth_client::setup` once,
//!    with the token and the finished key material, and reflecting
//!    whatever real reply comes back: `Step::Enrolled` (`ENROLLED`),
//!    `Step::TokenDenied` (`SETUP_DENIED`), `Step::EnrollFailed`
//!    (`ENROLL_FAILED <code>` — the .mli promises this does NOT burn
//!    the token, so `EnrollFailed` keeps the token around and lets the
//!    operator go straight back to `ChoosingKeySource` without
//!    restarting the wizard), or `Step::Failed` for anything at the
//!    transport/gpg layer (unreachable socket, no `gpg` on `PATH`,
//!    malformed paste, already-enrolled).
//!
//! Why "submit token" and "enroll key" aren't two separate network
//! round trips despite being two UI steps: see
//! `operator_auth_client.rs`'s own module doc. Short version — the
//! .mli's SETUP flow is one connection, bounded by the server's own
//! wall-clock deadline (10s by default), with no server-side state
//! that survives past it. Holding a connection open while the
//! operator pastes text or this process shells out to `gpg` would
//! race that deadline for no protocol benefit, so this module collects
//! both the token and the finished key material locally first, then
//! makes one `operator_auth_client::setup` call.

use std::fs;
use std::path::PathBuf;

use zeroize::Zeroizing;

use crate::operator_auth_client::{self, SetupError};

/// A fixed, honest identity string for a wizard-generated key — not an
/// attempt at a real email address. `generate_fresh_operator_key`'s
/// own before/after fingerprint diff (see its doc comment) is what
/// actually disambiguates repeated generate attempts, not uniqueness
/// of this string, so it doesn't need embedded timestamps/nonces.
const GENERATED_KEY_UID: &str = "foSSH operator (generated by setup wizard)";

/// Adversarial review: `push_paste_char`/`push_paste_str` had no cap,
/// so a very large accidental paste (an entire file dropped into the
/// terminal, a doubled/mangled paste event) could grow this buffer
/// without limit before the armored-key marker check or the socket
/// ever see it. Generous relative to any real key (a bare ed25519
/// signing key with no photo/UID art is a few hundred bytes; even a
/// large real-world key is well under 64 KiB) while still bounding
/// worst case to something trivial in memory.
const MAX_PASTE_LEN: usize = 262_144;

pub enum Step {
    /// No setup-token file at `token_path` — either the watchdog
    /// hasn't started yet (it writes this file on first start,
    /// §2.6/ADR-0057), setup already completed and burned it, or
    /// `FOSSH_SETUP_TOKEN_PATH` points somewhere wrong.
    NoTokenFound,
    /// The token file was read successfully; not yet submitted.
    ReadyToSubmit { plaintext: Zeroizing<String> },
    /// Token in hand, not yet sent anywhere — choosing how to supply
    /// the operator's public key.
    ChoosingKeySource { token: Zeroizing<String> },
    /// Raw armored-key-block text entry.
    PastingKey {
        token: Zeroizing<String>,
        input: Zeroizing<String>,
    },
    /// A fresh key was just generated (real `gpg`, real keyring — see
    /// module doc). Shown once before it's sent, per §3.11's own
    /// wording ("display the private half exactly once").
    KeyGenerated {
        token: Zeroizing<String>,
        fingerprint: String,
        private_key_armored: Zeroizing<String>,
        public_key_armored: String,
    },
    /// `ENROLLED <fingerprint>` — the real reply from the real
    /// watchdog. Setup is complete; the token file is gone.
    Enrolled { fingerprint: String },
    /// `SETUP_DENIED` — wrong/expired token, or nothing currently
    /// live server-side. Not retryable without a fresh token (a
    /// re-read of `token_path`, e.g. by relaunching this screen).
    TokenDenied,
    /// `ENROLL_FAILED <reason code>` — per the .mli, the token was
    /// deliberately NOT burned. `token` is kept so a retry can go
    /// straight back to choosing key material without re-reading the
    /// file or restarting the wizard.
    EnrollFailed {
        token: Zeroizing<String>,
        reason_code: String,
    },
    /// Anything else real: unreachable socket, no `gpg` on `PATH`, a
    /// malformed paste, an unreadable token file, or an already-
    /// enrolled key discovered mid-flow.
    Failed(String),
}

pub struct Wizard {
    pub step: Step,
    pub token_path: PathBuf,
}

impl Wizard {
    pub fn new(token_path: PathBuf) -> Self {
        let step = match fs::read_to_string(&token_path) {
            Ok(raw) => {
                let plaintext = raw.trim().to_string();
                if plaintext.is_empty() {
                    Step::Failed(format!(
                        "the setup token file at {} is empty",
                        token_path.display()
                    ))
                } else {
                    Step::ReadyToSubmit {
                        plaintext: Zeroizing::new(plaintext),
                    }
                }
            }
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => Step::NoTokenFound,
            Err(e) => Step::Failed(format!("reading the setup token file: {e}")),
        };
        Self { step, token_path }
    }

    /// Re-reads `token_path` from scratch — used to reset back to a
    /// clean starting state after a fatal failure (`TokenDenied`, an
    /// infra-level `Failed`), since those genuinely need a fresh look
    /// at the file rather than a resume of in-memory state.
    fn reload(&mut self) {
        *self = Self::new(self.token_path.clone());
    }

    pub fn proceed_to_key_source(&mut self) {
        if let Step::ReadyToSubmit { plaintext } = &self.step {
            self.step = Step::ChoosingKeySource {
                token: plaintext.clone(),
            };
        }
    }

    pub fn start_paste(&mut self) {
        if let Step::ChoosingKeySource { token } = &self.step {
            self.step = Step::PastingKey {
                token: token.clone(),
                input: Zeroizing::new(String::new()),
            };
        }
    }

    pub fn push_paste_char(&mut self, c: char) {
        if let Step::PastingKey { input, .. } = &mut self.step
            && input.len() < MAX_PASTE_LEN
        {
            input.push(c);
        }
    }

    /// Appends a whole chunk at once — what a bracketed-paste event
    /// delivers (`app.rs`'s `on_paste`), preserving the embedded
    /// newlines a real armored key block needs. Character-by-character
    /// entry (`push_paste_char`) still works for manual edits, but no
    /// human types a PGP key block one keystroke at a time.
    ///
    /// Truncates rather than rejecting outright on a paste that would
    /// cross `MAX_PASTE_LEN` — a real key ends well under the cap, so
    /// truncation only ever bites something already too large to be a
    /// real armored key, and `submit_pasted_key`'s own marker check
    /// still catches a truncated paste as malformed rather than
    /// silently forwarding a corrupt block.
    pub fn push_paste_str(&mut self, s: &str) {
        if let Step::PastingKey { input, .. } = &mut self.step {
            let room = MAX_PASTE_LEN.saturating_sub(input.len());
            if room == 0 {
                return;
            }
            // Truncate on a char boundary -- `s` is a real `&str`
            // (already valid UTF-8), so an arbitrary byte offset could
            // land mid-codepoint.
            let mut end = room.min(s.len());
            while end > 0 && !s.is_char_boundary(end) {
                end -= 1;
            }
            input.push_str(&s[..end]);
        }
    }

    pub fn backspace_paste(&mut self) {
        if let Step::PastingKey { input, .. } = &mut self.step {
            input.pop();
        }
    }

    pub fn cancel_paste(&mut self) {
        if let Step::PastingKey { token, .. } = &self.step {
            self.step = Step::ChoosingKeySource {
                token: token.clone(),
            };
        }
    }

    pub fn submit_pasted_key(&mut self) {
        let Step::PastingKey { token, input } = &self.step else {
            return;
        };
        let token = token.clone();
        let armored = input.clone();
        self.enroll(&token, &armored);
    }

    /// Blocking — real `gpg --quick-generate-key` against the
    /// operator's own default keyring. Same "explicit key press only"
    /// discipline `OperatorAuth::attempt` already established for this
    /// crate's other blocking-on-`gpg` call.
    pub fn generate_fresh_key(&mut self) {
        let Step::ChoosingKeySource { token } = &self.step else {
            return;
        };
        let token = token.clone();
        match operator_auth_client::generate_fresh_operator_key(GENERATED_KEY_UID) {
            Ok(generated) => {
                self.step = Step::KeyGenerated {
                    token,
                    fingerprint: generated.fingerprint,
                    private_key_armored: generated.private_key_armored,
                    public_key_armored: generated.public_key_armored,
                };
            }
            Err(e) => self.step = Step::Failed(format!("generating a fresh operator key: {e}")),
        }
    }

    /// Acknowledges having seen (and, implicitly, saved) the
    /// once-only private-key display, then sends the already-generated
    /// public key over the wire.
    pub fn acknowledge_generated_key(&mut self) {
        let Step::KeyGenerated {
            token,
            public_key_armored,
            ..
        } = &self.step
        else {
            return;
        };
        let token = token.clone();
        let public_key_armored = public_key_armored.clone();
        self.enroll(&token, &public_key_armored);
    }

    fn enroll(&mut self, token: &str, public_key_armored: &str) {
        self.step = match operator_auth_client::setup(token, public_key_armored) {
            Ok(fingerprint) => Step::Enrolled { fingerprint },
            Err(SetupError::TokenDenied) => Step::TokenDenied,
            Err(SetupError::EnrollFailed(reason_code)) => Step::EnrollFailed {
                token: Zeroizing::new(token.to_string()),
                reason_code,
            },
            Err(e) => Step::Failed(e.to_string()),
        };
    }

    /// From `EnrollFailed`: per the .mli the token was not burned, so
    /// this goes straight back to choosing key material with the same
    /// still-valid token — no re-read of the file, no restart.
    pub fn retry_after_enroll_failure(&mut self) {
        if let Step::EnrollFailed { token, .. } = &self.step {
            self.step = Step::ChoosingKeySource {
                token: token.clone(),
            };
        }
    }

    /// From a fatal state (`TokenDenied`, an infra-level `Failed`) —
    /// re-reads the token file rather than resuming, since those
    /// states have no still-valid in-memory token worth keeping.
    pub fn reset(&mut self) {
        self.reload();
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch_path(name: &str) -> PathBuf {
        std::env::temp_dir().join(format!(
            "fossh-tui-wizard-test-{name}-{}",
            std::process::id()
        ))
    }

    #[test]
    fn no_token_file_starts_at_no_token_found() {
        let path = scratch_path("fresh");
        let _ = std::fs::remove_file(&path);
        let wizard = Wizard::new(path);
        assert!(matches!(wizard.step, Step::NoTokenFound));
    }

    #[test]
    fn existing_token_file_starts_at_ready_to_submit_with_its_real_contents() {
        let path = scratch_path("preexisting");
        let _ = std::fs::remove_file(&path);
        std::fs::write(&path, "the-real-token\n").unwrap();
        let wizard = Wizard::new(path.clone());
        match &wizard.step {
            Step::ReadyToSubmit { plaintext } => assert_eq!(plaintext.as_str(), "the-real-token"),
            _ => panic!("expected ReadyToSubmit"),
        }
        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn an_empty_token_file_fails_cleanly_instead_of_submitting_an_empty_token() {
        let path = scratch_path("empty");
        let _ = std::fs::remove_file(&path);
        std::fs::write(&path, "").unwrap();
        let wizard = Wizard::new(path.clone());
        assert!(matches!(wizard.step, Step::Failed(_)));
        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn unreadable_token_file_fails_cleanly_instead_of_being_mistaken_for_absent() {
        use std::os::unix::fs::PermissionsExt;

        let path = scratch_path("unreadable");
        let _ = std::fs::remove_file(&path);
        std::fs::write(&path, "irrelevant").unwrap();
        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o000)).unwrap();

        if fs::read_to_string(&path).is_ok() {
            // Root or CAP_DAC_OVERRIDE can read a 0-permission file
            // anyway -- skip rather than false-fail there.
            std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o600)).unwrap();
            std::fs::remove_file(&path).ok();
            return;
        }

        let wizard = Wizard::new(path.clone());
        assert!(matches!(wizard.step, Step::Failed(_)));

        std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o600)).unwrap();
        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn proceed_to_key_source_carries_the_real_token_forward() {
        let path = scratch_path("proceed");
        std::fs::write(&path, "tok123").unwrap();
        let mut wizard = Wizard::new(path.clone());

        wizard.proceed_to_key_source();

        match &wizard.step {
            Step::ChoosingKeySource { token } => assert_eq!(token.as_str(), "tok123"),
            _ => panic!("expected ChoosingKeySource"),
        }
        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn pasting_key_text_accumulates_and_backspace_removes() {
        let path = scratch_path("paste");
        std::fs::write(&path, "tok123").unwrap();
        let mut wizard = Wizard::new(path.clone());
        wizard.proceed_to_key_source();
        wizard.start_paste();

        wizard.push_paste_str("-----BEGIN PGP PUBLIC KEY BLOCK-----\n");
        wizard.push_paste_char('x');
        wizard.backspace_paste();

        match &wizard.step {
            Step::PastingKey { input, .. } => {
                assert_eq!(input.as_str(), "-----BEGIN PGP PUBLIC KEY BLOCK-----\n")
            }
            _ => panic!("expected PastingKey"),
        }
        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn pasting_never_grows_the_buffer_past_max_paste_len() {
        // Adversarial review: an unbounded paste buffer (an entire
        // file dropped into the terminal, a doubled paste event) could
        // grow without limit before ever reaching the armored-key
        // marker check. Regression test for the cap.
        let path = scratch_path("paste-cap");
        std::fs::write(&path, "tok123").unwrap();
        let mut wizard = Wizard::new(path.clone());
        wizard.proceed_to_key_source();
        wizard.start_paste();

        let huge_chunk = "a".repeat(MAX_PASTE_LEN + 10_000);
        wizard.push_paste_str(&huge_chunk);
        // A further push once already at the cap must also be a no-op,
        // not silently grow past it via a second call.
        wizard.push_paste_str("more");
        wizard.push_paste_char('x');

        match &wizard.step {
            Step::PastingKey { input, .. } => {
                assert!(
                    input.len() <= MAX_PASTE_LEN,
                    "paste buffer must never exceed MAX_PASTE_LEN, got {} bytes",
                    input.len()
                );
            }
            _ => panic!("expected PastingKey"),
        }
        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn pasting_truncates_on_a_real_utf8_char_boundary() {
        // A naive byte-offset truncation could split a multi-byte
        // UTF-8 character in half, which would then panic on the
        // `&str` slice itself rather than degrade gracefully.
        let path = scratch_path("paste-utf8-boundary");
        std::fs::write(&path, "tok123").unwrap();
        let mut wizard = Wizard::new(path.clone());
        wizard.proceed_to_key_source();
        wizard.start_paste();

        // Fill to one byte short of the cap with ASCII, then push a
        // multi-byte character that would straddle the boundary.
        wizard.push_paste_str(&"a".repeat(MAX_PASTE_LEN - 1));
        wizard.push_paste_str("€"); // 3-byte UTF-8 character

        match &wizard.step {
            Step::PastingKey { input, .. } => {
                assert!(input.len() <= MAX_PASTE_LEN);
                // Must still be valid UTF-8 -- proven by construction
                // (`input` is a `String`), but assert explicitly that
                // this didn't panic and produced a sane result.
                assert!(input.starts_with('a'));
            }
            _ => panic!("expected PastingKey"),
        }
        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn cancel_paste_returns_to_choosing_key_source_with_the_token_intact() {
        let path = scratch_path("cancel-paste");
        std::fs::write(&path, "tok123").unwrap();
        let mut wizard = Wizard::new(path.clone());
        wizard.proceed_to_key_source();
        wizard.start_paste();
        wizard.push_paste_char('x');

        wizard.cancel_paste();

        match &wizard.step {
            Step::ChoosingKeySource { token } => assert_eq!(token.as_str(), "tok123"),
            _ => panic!("expected ChoosingKeySource"),
        }
        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn submitting_a_malformed_pasted_key_fails_without_a_live_watchdog() {
        let path = scratch_path("submit-malformed");
        std::fs::write(&path, "tok123").unwrap();
        let mut wizard = Wizard::new(path.clone());
        wizard.proceed_to_key_source();
        wizard.start_paste();
        wizard.push_paste_str("not a real key");

        wizard.submit_pasted_key();

        assert!(
            matches!(wizard.step, Step::Failed(_)),
            "a malformed paste must be caught client-side, not left pending forever"
        );
        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn submitting_against_an_unreachable_socket_fails_honestly() {
        // No real watchdog running in this test environment -- proves
        // the wizard reports a real, honest failure rather than
        // silently pretending to succeed. Relies on the real default
        // socket path genuinely not existing here, same reasoning
        // app.rs's own `a_on_the_operator_auth_screen_triggers_an_attempt`
        // test already uses (this crate is `#![forbid(unsafe_code)]`,
        // so env::set_var to override the socket path isn't available
        // to a test either).
        let path = scratch_path("submit-unreachable");
        std::fs::write(&path, "tok123").unwrap();
        let mut wizard = Wizard::new(path.clone());
        wizard.proceed_to_key_source();
        wizard.start_paste();
        wizard.push_paste_str(
            "-----BEGIN PGP PUBLIC KEY BLOCK-----\nx\n-----END PGP PUBLIC KEY BLOCK-----\n",
        );

        wizard.submit_pasted_key();

        assert!(matches!(wizard.step, Step::Failed(_)));
        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn retry_after_enroll_failure_keeps_the_same_token_and_goes_back_to_choosing_key_source() {
        let path = scratch_path("retry-enroll-failed");
        std::fs::write(&path, "tok123").unwrap();
        let mut wizard = Wizard::new(path.clone());
        wizard.proceed_to_key_source();
        wizard.step = Step::EnrollFailed {
            token: Zeroizing::new("tok123".to_string()),
            reason_code: "invalid_key".to_string(),
        };

        wizard.retry_after_enroll_failure();

        match &wizard.step {
            Step::ChoosingKeySource { token } => assert_eq!(token.as_str(), "tok123"),
            _ => panic!("expected ChoosingKeySource, retry must not require restarting the wizard"),
        }
        std::fs::remove_file(&path).ok();
    }

    #[test]
    fn reset_rereads_the_token_file_from_scratch() {
        let path = scratch_path("reset");
        std::fs::write(&path, "tok123").unwrap();
        let mut wizard = Wizard::new(path.clone());
        wizard.step = Step::TokenDenied;

        wizard.reset();

        match &wizard.step {
            Step::ReadyToSubmit { plaintext } => assert_eq!(plaintext.as_str(), "tok123"),
            _ => panic!("expected ReadyToSubmit after reset"),
        }
        std::fs::remove_file(&path).ok();
    }

}
