//! First-run setup (§2.6/§3.11), driven now by `fossh-console` over
//! the agent protocol rather than by a terminal UI.
//!
//! The protocol logic is unchanged from the `wizard.rs` this replaces
//! (ADR-0059): the token is read straight off disk — the watchdog is
//! the only thing that ever writes it — and every verify/burn decision
//! belongs to the real watchdog, not to this process. What is gone is
//! the paste buffer, the keystroke handling, and the per-step screen
//! state, all of which were terminal concerns that GTK's own text view
//! now owns.
//!
//! ## The setup token deliberately never crosses to the console
//!
//! `state()` reports only *whether* a usable token was found. The
//! plaintext stays in this process, in a `Zeroizing<String>`, and
//! `enroll` supplies it from there. Handing it to Python instead would
//! have put a live credential into an interpreter that cannot zeroize
//! a `str`, that may copy it during garbage collection, and that can
//! serialise it into a traceback — for no benefit, since the console
//! has nothing to do with the value but hand it straight back. See
//! ADR-0061.

use std::fs;
use std::path::PathBuf;

use zeroize::Zeroizing;

use crate::operator_auth_client::{self, SetupError};

/// A fixed, honest identity string for a generated key — not an attempt
/// at a real email address. `generate_fresh_operator_key`'s own
/// before/after fingerprint diff (see its doc comment) is what
/// disambiguates repeated generate attempts, so this string does not
/// need embedded timestamps or nonces.
const GENERATED_KEY_UID: &str = "foSSH operator (generated by setup wizard)";

/// A ceiling on the armored public key the console may submit.
/// Inherited from the paste cap the terminal wizard enforced, and it
/// keeps doing the same job one layer further out: a real armored key
/// is a few hundred bytes, and even a large one with photo IDs is well
/// under 64 KiB, so anything past this is a mistaken paste rather than
/// a key.
pub const MAX_KEY_LEN: usize = 262_144;

/// What the console is allowed to know about the token's existence.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum State {
    /// No setup-token file — the watchdog has not started yet, setup
    /// already completed and burned it, or the path is wrong.
    NoToken,
    /// A usable token is in hand. Its value is not reported.
    Ready,
    /// Enrollment already succeeded in this process's lifetime.
    Enrolled,
    /// The file exists but could not be used (empty, unreadable).
    Unusable,
}

impl State {
    pub fn as_str(self) -> &'static str {
        match self {
            State::NoToken => "no_token",
            State::Ready => "ready",
            State::Enrolled => "enrolled",
            State::Unusable => "unusable",
        }
    }
}

pub struct Setup {
    token: Option<Zeroizing<String>>,
    state: State,
    /// Present only for `Unusable`, and written for a human.
    detail: Option<String>,
    enrolled_fingerprint: Option<String>,
    pub token_path: PathBuf,
}

impl Setup {
    pub fn new(token_path: PathBuf) -> Self {
        let mut this = Self {
            token: None,
            state: State::NoToken,
            detail: None,
            enrolled_fingerprint: None,
            token_path,
        };
        this.reload();
        this
    }

    /// Re-reads the token file from scratch. The console calls this
    /// after starting the watchdog for the first time, since the file
    /// appears only once the watchdog has run.
    pub fn reload(&mut self) {
        self.token = None;
        self.enrolled_fingerprint = None;
        self.detail = None;
        match fs::read_to_string(&self.token_path) {
            Ok(raw) => {
                let plaintext = raw.trim().to_string();
                if plaintext.is_empty() {
                    self.state = State::Unusable;
                    self.detail = Some(format!(
                        "the setup token file at {} is empty",
                        self.token_path.display()
                    ));
                } else {
                    self.token = Some(Zeroizing::new(plaintext));
                    self.state = State::Ready;
                }
            }
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                self.state = State::NoToken;
            }
            Err(e) => {
                self.state = State::Unusable;
                self.detail = Some(format!("reading the setup token file: {e}"));
            }
        }
    }

    pub fn state(&self) -> State {
        self.state
    }

    pub fn detail(&self) -> Option<&str> {
        self.detail.as_deref()
    }

    pub fn enrolled_fingerprint(&self) -> Option<&str> {
        self.enrolled_fingerprint.as_deref()
    }

    /// Blocking — a real `gpg --quick-generate-key` against the
    /// operator's own default keyring. The private half comes back so
    /// the console can show it exactly once, per §3.11's own wording;
    /// it is never written anywhere by this process.
    pub fn generate_key(&self) -> Result<operator_auth_client::GeneratedOperatorKey, String> {
        operator_auth_client::generate_fresh_operator_key(GENERATED_KEY_UID)
            .map_err(|e| format!("generating a fresh operator key: {e}"))
    }

    /// One `operator_auth_client::setup` call with the token this
    /// process is holding and the key material the console supplied.
    ///
    /// Why token and key go over the wire together despite being two
    /// steps in the interface: the watchdog's SETUP flow is one
    /// connection bounded by the server's own wall-clock deadline, with
    /// no server-side state that survives it. Holding a connection open
    /// while a human pastes a key would race that deadline for no
    /// protocol benefit.
    pub fn enroll(&mut self, public_key_armored: &str) -> Result<String, EnrollOutcome> {
        if public_key_armored.len() > MAX_KEY_LEN {
            return Err(EnrollOutcome::Invalid(format!(
                "that public key is {} bytes; a real armored key is far under {MAX_KEY_LEN}",
                public_key_armored.len()
            )));
        }
        let Some(token) = self.token.clone() else {
            return Err(EnrollOutcome::Invalid(
                "there is no usable setup token on this install — start the watchdog once, then \
                 reload"
                    .to_string(),
            ));
        };

        match operator_auth_client::setup(&token, public_key_armored) {
            Ok(fingerprint) => {
                // The watchdog has burned the token; holding the now-
                // dead plaintext any longer serves nothing.
                self.token = None;
                self.state = State::Enrolled;
                self.enrolled_fingerprint = Some(fingerprint.clone());
                Ok(fingerprint)
            }
            Err(SetupError::TokenDenied) => {
                // Denied means this token is not the live one. Dropping
                // it forces a genuine re-read rather than letting the
                // console retry the same dead value forever.
                self.token = None;
                self.state = State::Unusable;
                self.detail = Some(
                    "the watchdog refused that setup token — it is not the one currently live"
                        .to_string(),
                );
                Err(EnrollOutcome::Denied)
            }
            // Per the `.mli`, `ENROLL_FAILED` explicitly does *not*
            // burn the token, so the token is kept and the console can
            // retry with different key material immediately.
            Err(SetupError::EnrollFailed(code)) => Err(EnrollOutcome::EnrollFailed(code)),
            Err(e) => Err(EnrollOutcome::Failed(e.to_string())),
        }
    }
}

#[derive(Debug)]
pub enum EnrollOutcome {
    /// The console sent something this process rejected before any
    /// network call.
    Invalid(String),
    /// `SETUP_DENIED`.
    Denied,
    /// `ENROLL_FAILED <code>` — token not burned, retry is meaningful.
    EnrollFailed(String),
    /// Transport, `gpg`, or an already-enrolled key.
    Failed(String),
}

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch_path(name: &str) -> PathBuf {
        std::env::temp_dir().join(format!(
            "fossh-agent-setup-test-{name}-{}",
            std::process::id()
        ))
    }

    #[test]
    fn no_token_file_reports_no_token() {
        let path = scratch_path("fresh");
        let _ = fs::remove_file(&path);
        assert_eq!(Setup::new(path).state(), State::NoToken);
    }

    #[test]
    fn an_existing_token_reports_ready_without_ever_exposing_its_value() {
        let path = scratch_path("preexisting");
        fs::write(&path, "the-real-token\n").unwrap();
        let setup = Setup::new(path.clone());
        assert_eq!(setup.state(), State::Ready);
        // The whole point of the split: nothing public on this type
        // returns the token. `detail` is the only string it hands out
        // in this state, and it is None.
        assert_eq!(setup.detail(), None);
        fs::remove_file(&path).ok();
    }

    #[test]
    fn an_empty_token_file_is_unusable_rather_than_submitted_as_an_empty_token() {
        let path = scratch_path("empty");
        fs::write(&path, "   \n").unwrap();
        let setup = Setup::new(path.clone());
        assert_eq!(setup.state(), State::Unusable);
        assert!(setup.detail().unwrap().contains("empty"));
        fs::remove_file(&path).ok();
    }

    #[test]
    fn an_unreadable_token_file_is_unusable_rather_than_mistaken_for_absent() {
        use std::os::unix::fs::PermissionsExt;
        let path = scratch_path("unreadable");
        fs::write(&path, "irrelevant").unwrap();
        fs::set_permissions(&path, fs::Permissions::from_mode(0o000)).unwrap();

        if fs::read_to_string(&path).is_ok() {
            // Root can read a 0-permission file; skip rather than
            // false-fail there.
            fs::set_permissions(&path, fs::Permissions::from_mode(0o600)).unwrap();
            fs::remove_file(&path).ok();
            return;
        }
        assert_eq!(Setup::new(path.clone()).state(), State::Unusable);
        fs::set_permissions(&path, fs::Permissions::from_mode(0o600)).unwrap();
        fs::remove_file(&path).ok();
    }

    #[test]
    fn enrolling_without_a_token_is_refused_before_any_network_call() {
        let path = scratch_path("no-token-enroll");
        let _ = fs::remove_file(&path);
        let mut setup = Setup::new(path);
        let armored = "-----BEGIN PGP PUBLIC KEY BLOCK-----\nx\n\
                       -----END PGP PUBLIC KEY BLOCK-----\n";
        assert!(matches!(
            setup.enroll(armored),
            Err(EnrollOutcome::Invalid(_))
        ));
    }

    #[test]
    fn an_oversized_key_is_refused_before_any_network_call() {
        let path = scratch_path("oversized");
        fs::write(&path, "tok123").unwrap();
        let mut setup = Setup::new(path.clone());
        let huge = "a".repeat(MAX_KEY_LEN + 1);
        assert!(matches!(setup.enroll(&huge), Err(EnrollOutcome::Invalid(_))));
        // The token must survive a rejection that never reached the
        // watchdog — otherwise a fat-fingered paste would cost the
        // operator their one live token.
        assert_eq!(setup.state(), State::Ready);
        fs::remove_file(&path).ok();
    }

    #[test]
    fn enrolling_against_an_unreachable_watchdog_fails_honestly_and_keeps_the_token() {
        // No watchdog runs in this environment, so this exercises the
        // real transport failure path. The token must be kept: nothing
        // server-side saw it, so it is still the live one.
        let path = scratch_path("unreachable");
        fs::write(&path, "tok123").unwrap();
        let mut setup = Setup::new(path.clone());
        let armored = "-----BEGIN PGP PUBLIC KEY BLOCK-----\nx\n\
                       -----END PGP PUBLIC KEY BLOCK-----\n";
        match setup.enroll(armored) {
            Err(EnrollOutcome::Failed(_)) => {}
            other => panic!("expected a transport-level failure, got {other:?}"),
        }
        assert_eq!(
            setup.state(),
            State::Ready,
            "a failure that never reached the watchdog must not discard the live token"
        );
        fs::remove_file(&path).ok();
    }

    #[test]
    fn reload_picks_up_a_token_that_appeared_after_construction() {
        // The real sequence on a fresh install: the console starts
        // before the watchdog has ever run, so the file does not exist
        // yet and appears later.
        let path = scratch_path("appears-later");
        let _ = fs::remove_file(&path);
        let mut setup = Setup::new(path.clone());
        assert_eq!(setup.state(), State::NoToken);

        fs::write(&path, "tok-appeared").unwrap();
        setup.reload();
        assert_eq!(setup.state(), State::Ready);
        fs::remove_file(&path).ok();
    }
}
