use std::fs;
use std::path::PathBuf;

use zeroize::Zeroizing;

use crate::operator_auth_client::{self, SetupError};

const GENERATED_KEY_UID: &str = "foSSH operator (generated by setup wizard)";

pub const MAX_KEY_LEN: usize = 262_144;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum State {

    NoToken,

    Ready,

    Enrolled,

    Unusable,
}

impl State {
    pub fn as_str(self) -> &'static str {
        match self {
            State::NoToken => "no_token",
            State::Ready => "ready",
            State::Enrolled => "enrolled",
            State::Unusable => "unusable",
        }
    }
}

pub struct Setup {
    token: Option<Zeroizing<String>>,
    state: State,

    detail: Option<String>,
    enrolled_fingerprint: Option<String>,
    pub token_path: PathBuf,
}

impl Setup {
    pub fn new(token_path: PathBuf) -> Self {
        let mut this = Self {
            token: None,
            state: State::NoToken,
            detail: None,
            enrolled_fingerprint: None,
            token_path,
        };
        this.reload();
        this
    }

    pub fn reload(&mut self) {
        self.token = None;
        self.enrolled_fingerprint = None;
        self.detail = None;
        match fs::read_to_string(&self.token_path) {
            Ok(raw) => {
                let plaintext = raw.trim().to_string();
                if plaintext.is_empty() {
                    self.state = State::Unusable;
                    self.detail = Some(format!(
                        "the setup token file at {} is empty",
                        self.token_path.display()
                    ));
                } else {
                    self.token = Some(Zeroizing::new(plaintext));
                    self.state = State::Ready;
                }
            }
            Err(e) if e.kind() == std::io::ErrorKind::NotFound => {
                self.state = State::NoToken;
            }
            Err(e) => {
                self.state = State::Unusable;
                self.detail = Some(format!("reading the setup token file: {e}"));
            }
        }
    }

    pub fn state(&self) -> State {
        self.state
    }

    pub fn detail(&self) -> Option<&str> {
        self.detail.as_deref()
    }

    pub fn enrolled_fingerprint(&self) -> Option<&str> {
        self.enrolled_fingerprint.as_deref()
    }

    pub fn generate_key(&self) -> Result<operator_auth_client::GeneratedOperatorKey, String> {
        operator_auth_client::generate_fresh_operator_key(GENERATED_KEY_UID)
            .map_err(|e| format!("generating a fresh operator key: {e}"))
    }

    pub fn enroll(&mut self, public_key_armored: &str) -> Result<String, EnrollOutcome> {
        if public_key_armored.len() > MAX_KEY_LEN {
            return Err(EnrollOutcome::Invalid(format!(
                "that public key is {} bytes; a real armored key is far under {MAX_KEY_LEN}",
                public_key_armored.len()
            )));
        }
        let Some(token) = self.token.clone() else {
            return Err(EnrollOutcome::Invalid(
                "there is no usable setup token on this install — start the watchdog once, then \
                 reload"
                    .to_string(),
            ));
        };

        match operator_auth_client::setup(&token, public_key_armored) {
            Ok(fingerprint) => {

                self.token = None;
                self.state = State::Enrolled;
                self.enrolled_fingerprint = Some(fingerprint.clone());
                Ok(fingerprint)
            }
            Err(SetupError::TokenDenied) => {

                self.token = None;
                self.state = State::Unusable;
                self.detail = Some(
                    "the watchdog refused that setup token — it is not the one currently live"
                        .to_string(),
                );
                Err(EnrollOutcome::Denied)
            }

            Err(SetupError::EnrollFailed(code)) => Err(EnrollOutcome::EnrollFailed(code)),
            Err(e) => Err(EnrollOutcome::Failed(e.to_string())),
        }
    }
}

#[derive(Debug)]
pub enum EnrollOutcome {

    Invalid(String),

    Denied,

    EnrollFailed(String),

    Failed(String),
}

#[cfg(test)]
mod tests {
    use super::*;

    fn scratch_path(name: &str) -> PathBuf {
        std::env::temp_dir().join(format!(
            "fossh-agent-setup-test-{name}-{}",
            std::process::id()
        ))
    }

    #[test]
    fn no_token_file_reports_no_token() {
        let path = scratch_path("fresh");
        let _ = fs::remove_file(&path);
        assert_eq!(Setup::new(path).state(), State::NoToken);
    }

    #[test]
    fn an_existing_token_reports_ready_without_ever_exposing_its_value() {
        let path = scratch_path("preexisting");
        fs::write(&path, "the-real-token\n").unwrap();
        let setup = Setup::new(path.clone());
        assert_eq!(setup.state(), State::Ready);

        assert_eq!(setup.detail(), None);
        fs::remove_file(&path).ok();
    }

    #[test]
    fn an_empty_token_file_is_unusable_rather_than_submitted_as_an_empty_token() {
        let path = scratch_path("empty");
        fs::write(&path, "   \n").unwrap();
        let setup = Setup::new(path.clone());
        assert_eq!(setup.state(), State::Unusable);
        assert!(setup.detail().unwrap().contains("empty"));
        fs::remove_file(&path).ok();
    }

    #[test]
    fn an_unreadable_token_file_is_unusable_rather_than_mistaken_for_absent() {
        use std::os::unix::fs::PermissionsExt;
        let path = scratch_path("unreadable");
        fs::write(&path, "irrelevant").unwrap();
        fs::set_permissions(&path, fs::Permissions::from_mode(0o000)).unwrap();

        if fs::read_to_string(&path).is_ok() {

            fs::set_permissions(&path, fs::Permissions::from_mode(0o600)).unwrap();
            fs::remove_file(&path).ok();
            return;
        }
        assert_eq!(Setup::new(path.clone()).state(), State::Unusable);
        fs::set_permissions(&path, fs::Permissions::from_mode(0o600)).unwrap();
        fs::remove_file(&path).ok();
    }

    #[test]
    fn enrolling_without_a_token_is_refused_before_any_network_call() {
        let path = scratch_path("no-token-enroll");
        let _ = fs::remove_file(&path);
        let mut setup = Setup::new(path);
        let armored = "-----BEGIN PGP PUBLIC KEY BLOCK-----\nx\n\
                       -----END PGP PUBLIC KEY BLOCK-----\n";
        assert!(matches!(
            setup.enroll(armored),
            Err(EnrollOutcome::Invalid(_))
        ));
    }

    #[test]
    fn an_oversized_key_is_refused_before_any_network_call() {
        let path = scratch_path("oversized");
        fs::write(&path, "tok123").unwrap();
        let mut setup = Setup::new(path.clone());
        let huge = "a".repeat(MAX_KEY_LEN + 1);
        assert!(matches!(
            setup.enroll(&huge),
            Err(EnrollOutcome::Invalid(_))
        ));

        assert_eq!(setup.state(), State::Ready);
        fs::remove_file(&path).ok();
    }

    #[test]
    fn enrolling_against_an_unreachable_watchdog_fails_honestly_and_keeps_the_token() {

        let path = scratch_path("unreachable");
        fs::write(&path, "tok123").unwrap();
        let mut setup = Setup::new(path.clone());
        let armored = "-----BEGIN PGP PUBLIC KEY BLOCK-----\nx\n\
                       -----END PGP PUBLIC KEY BLOCK-----\n";
        match setup.enroll(armored) {
            Err(EnrollOutcome::Failed(_)) => {}
            other => panic!("expected a transport-level failure, got {other:?}"),
        }
        assert_eq!(
            setup.state(),
            State::Ready,
            "a failure that never reached the watchdog must not discard the live token"
        );
        fs::remove_file(&path).ok();
    }

    #[test]
    fn reload_picks_up_a_token_that_appeared_after_construction() {

        let path = scratch_path("appears-later");
        let _ = fs::remove_file(&path);
        let mut setup = Setup::new(path.clone());
        assert_eq!(setup.state(), State::NoToken);

        fs::write(&path, "tok-appeared").unwrap();
        setup.reload();
        assert_eq!(setup.state(), State::Ready);
        fs::remove_file(&path).ok();
    }
}
