/* foSSH C ABI (§11). Generated by cbindgen from crates/fossh-ffi/src/lib.rs — do not edit by hand. */

#ifndef FOSSH_H
#define FOSSH_H

/* This file is generated by cbindgen. Do not edit it manually; edit crates/fossh-ffi/src/lib.rs and regenerate instead. */

#include "stdint.h"
#include "stddef.h"

/**
 * §11: "`fossh_abi_version()` returns a `u32` the bindings check at
 * load." Bump on any breaking change to the functions below.
 */
#define FOSSH_ABI_VERSION 1

/**
 * Stable, versioned error codes (§11), exported as `fossh_err_t` in the
 * generated header so C callers get symbolic names instead of bare
 * magic numbers. Negative on every rejection path; `0` is success.
 * Never carries a dynamic message — `fossh_last_error` maps each
 * variant to one of a fixed set of strings, on purpose: S2 forbids
 * leaking anything caller-controlled (a name, a path, a JSON parse
 * error naming a byte offset into the caller's own data) back across a
 * boundary whose whole point is not to have a body/message channel for
 * the ingest path. The enum *definition* — fixed, compile-time-known
 * variant names — is not that; only a dynamic runtime string built from
 * caller input would be.
 */
enum fossh_err_t
#if defined(__cplusplus) || __STDC_VERSION__ >= 202311L
  : int32_t
#endif // defined(__cplusplus) || __STDC_VERSION__ >= 202311L
 {
  /**
   * A panic was caught at the FFI boundary, or another truly
   * unexpected internal failure (a poisoned mutex, a clock error).
   */
  FOSSH_ERR_T_INTERNAL = -1,
  /**
   * A required pointer was null, not valid UTF-8, or otherwise
   * malformed (oversized `props_json`, a `key` that doesn't parse as
   * `fossh_<slug>_<base32>`, ...).
   */
  FOSSH_ERR_T_INVALID_ARGUMENT = -2,
  /**
   * A recording function was called before `fossh_set_key` succeeded.
   */
  FOSSH_ERR_T_NO_KEY_SET = -3,
  /**
   * `fossh_set_key`: the presented key doesn't match any known,
   * enabled site.
   */
  FOSSH_ERR_T_UNAUTHORIZED = -4,
  /**
   * The event name or a property key isn't on the site's allowlist,
   * or a field failed its grammar/bound validation (P8, S4).
   */
  FOSSH_ERR_T_REJECTED = -5,
  /**
   * The event (or batch) exceeds S4's size caps.
   */
  FOSSH_ERR_T_TOO_LARGE = -6,
  /**
   * S10's per-site token bucket is empty.
   */
  FOSSH_ERR_T_RATE_LIMITED = -7,
  /**
   * The spool or database write itself failed.
   */
  FOSSH_ERR_T_WRITE_FAILED = -8,
};
#ifndef __cplusplus
#if __STDC_VERSION__ >= 202311L
typedef enum fossh_err_t fossh_err_t;
#else
typedef int32_t fossh_err_t;
#endif // __STDC_VERSION__ >= 202311L
#endif // __cplusplus

/**
 * Opaque handle (`fossh_ctx*` in the C header). All mutable state is
 * behind one `Mutex`, held only across the write path (§11: "internal
 * state behind a `Mutex` on the write path only").
 *
 * Named exactly `fossh_ctx` (not idiomatic Rust `UpperCamelCase`) on
 * purpose: `§11`'s header sketch spells the C typedef `fossh_ctx`, and
 * `cbindgen` (M8) uses a type's Rust name verbatim unless told to rename
 * it — matching the spec's spelling here means one less thing to
 * configure, and a struct that appears in `include/fossh.h` exactly as
 * C code expects to write it.
 */
typedef struct fossh_ctx fossh_ctx;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

 uint32_t fossh_abi_version(void);

/**
 * # Safety
 * `config_path`, if non-null, must point to a valid, NUL-terminated,
 * UTF-8 C string that remains valid for the duration of this call only
 * (§11: "borrowed for the call only; foSSH copies what it keeps").
 */
 struct fossh_ctx *fossh_init(const char *config_path);

/**
 * # Safety
 * `ctx` must be either null (a no-op) or a pointer previously returned by
 * `fossh_init` and not yet passed to `fossh_free`.
 */
 void fossh_free(struct fossh_ctx *ctx);

/**
 * # Safety
 * `ctx` must be a valid, non-null pointer from `fossh_init`. `buf` must
 * point to at least `len` writable bytes (or `len` may be `0`, in which
 * case `buf` is never dereferenced).
 */
 int32_t fossh_last_error(const struct fossh_ctx *ctx, char *buf, size_t len);

/**
 * # Safety
 * `ctx` must be valid and non-null. `key` must be a valid, NUL-terminated,
 * UTF-8 C string, borrowed for this call only.
 */
 int32_t fossh_set_key(struct fossh_ctx *ctx, const char *key);

/**
 * # Safety
 * `ctx` must be valid and non-null. `path`, `referrer`, `client_ip`,
 * `user_agent` — each either null or a valid NUL-terminated UTF-8 C
 * string, borrowed for this call only.
 */

int32_t fossh_pageview(struct fossh_ctx *ctx,
                       const char *path,
                       const char *referrer,
                       const char *client_ip,
                       const char *user_agent);

/**
 * # Safety
 * `ctx` must be valid and non-null. `name` must be a valid NUL-terminated
 * UTF-8 C string. `props_json`, if non-null, must be a valid
 * NUL-terminated UTF-8 C string holding a JSON object of string values,
 * at most 1 KiB. All borrowed for this call only.
 */

int32_t fossh_event(struct fossh_ctx *ctx,
                    const char *name,
                    int64_t value,
                    const char *props_json);

/**
 * # Safety
 * `ctx` must be valid and non-null. `name` must be a valid NUL-terminated
 * UTF-8 C string, borrowed for this call only.
 */
 int32_t fossh_timing(struct fossh_ctx *ctx, const char *name, int64_t millis);

/**
 * CGI-style entry point: hand foSSH a raw request environment (`envp`,
 * `envc` entries shaped `KEY=VALUE`, matching RFC 3875 var names — see
 * `fossh-cgi`) and a body; foSSH extracts method/path/headers itself and
 * runs the same allowlist/validation/opt-out pipeline as every other
 * transport. A non-empty body is parsed as a JSON event or batch
 * (mirroring `POST /e`); an empty body falls back to `QUERY_STRING`
 * (mirroring `GET /e.gif`).
 *
 * # Safety
 * `ctx` must be valid and non-null. `envp` must point to `envc` valid,
 * NUL-terminated UTF-8 C strings (or `envc` may be `0`, in which case
 * `envp` is never read). `body` must point to at least `body_len` bytes
 * (or `body_len` may be `0`, in which case `body` may be null). All
 * borrowed for this call only.
 */

int32_t fossh_record_env(struct fossh_ctx *ctx,
                         const char *const *envp,
                         size_t envc,
                         const uint8_t *body,
                         size_t body_len);

/**
 * "Force spool/tx flush; safe to call at shutdown" (§11). For
 * `mode = "direct"` there is nothing to flush — `record_event` commits
 * its own transaction per call. For `mode = "spool"`, drains everything
 * queued for this site straight into the database immediately, rather
 * than waiting for the next `fossh maintain`/compactor cycle — so a host
 * process that calls this before exiting never strands events in the spool.
 *
 * # Safety
 * `ctx` must be valid and non-null.
 */
 int32_t fossh_flush(struct fossh_ctx *ctx);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* FOSSH_H */
